import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Link from 'next/link';
import { TbCurrencySolana } from 'react-icons/tb';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>NIL: Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex items-center justify-center h-screen">
                <main>
                    <h1 className="text-center text-xl pb-4">
                        Solana Portfolio
                    </h1>
                    <div className="flex justify-center text-3xl pb-4">
                        <TbCurrencySolana />
                    </div>
                    <p className='text-sm font-thin'>
                        Look at your <Link href={'/dashboard'}><a className="link">Token Dashboard</a></Link> and <em>do stuff</em>.
                    </p>
                </main>
            </div>

        </div>
    );
};

export default Home;
