import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Link from 'next/link';
import { TbCurrencySolana } from 'react-icons/tb';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>NIL: Probably Nothing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex-1 flex items-center justify-center pt-24"> {/* Centering content */}
                <main>
                    <h1 className="text-center text-xl pb-4">
                        NIL
                    </h1>
                    <div className="flex justify-center text-3xl pb-4">
                        ∅
                    </div>
                    <p className='text-sm font-thin'>
                        Load the <Link href={'/dashboard'}><a className="link">Wallet Browser</a></Link> and manage your portfolio.
                    </p>
                    <p className='text-sm font-thin'>
                        View your <Link href={'/transaction-history'}><a className="link">Transaction History</a></Link> and generate reports.
                    </p>
                    <p className='text-sm font-thin'>
                        Mint a  <Link href={'/nil'}><a className="link">NIL NFT</a></Link> license.
                    </p>
                </main>
            </div>
        </div>
    );
};

export default Home;
